# Generated by Django 5.1.3 on 2024-11-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='Author',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Développement Personnel et Soft Skills', 'Developpement'), ('Business et Entrepreneuriat', 'Business'), ('Compétences Digitales', 'Competences'), ('Informatique et Programmation', 'Informatique'), ('Langues et Communication', 'Langues'), ('Santé et Bien-être', 'Sante'), ('Art et Créativité', 'Art'), ('Sciences et Éducation', 'Sciences')], max_length=38),
        ),
    ]
